### ISSUE TITLE
Userモデルの作成

### ISSUE THREAD

**Issue by guni973** [guni973/hayaoki#2]
以下のようにモデルを定義する

テーブル名: User

|Column|Type|Other|
|----|----|----|
|screen_name|string|not null|
|user_id|string|not null|
|image_url|string||
|attendance_rate|double||
|accept_count|int|承認者が承認した回数|
|is_player|bool|not null|

screen_name, user_id, image_urlは、Twitter連携した際に値を代入する

**Comment by dayaman** [comment]
🙋‍♂️
